steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run', 'deploy', 'asteroids-extractor',
        '--source', '.',
        '--region', 'us-central1',
        '--allow-unauthenticated',
        '--gen2',
        '--runtime', 'python312',
        '--entry-point', 'main'
      ]
timeout: '900s'
